### PR TITLE
Displaying mobbr button in question lists

### PR DESCRIPTION
**Pull request by pupi1985**
This should get the job done without requiring the Q2A core to be modified as requested here https://github.com/q2a/question2answer/issues/157.

The branch is actually untested as I don't know anything about mobbr. However, I haven't made any change in the logic so it should work the same as before.

It is important to note that the button has to be customized per theme, as I explained in the linked ticket. In case of the SnowFlat (Q2A v1.7) theme it seems to be working without any code change:

mobbr1

In case of the Snow (Q2A v1.6) theme I had to add this CSS fix:

``` css
.qa-q-item-main {
    width: 440px;
}
```

mobbr-2

### CODE REVIEW

**Comment by patricksavalle** [comment]
Super :)

We will be looking into this tomorrow. I will revoke the pledge on the other item and reward this item as soon as we pulled the issue. Will post instructions to collect your reward, in this thread.

**Comment by patricksavalle** [comment]
Hi @pupi1985 we tried it on our own ask.mobbr.com and it works fine except for one tiny, tiny but totally essential thing :)

Is it possible you add to each button the URL of the question? That's on line 11 of qa-mobbr-frontend.php

```
        $buttonhtml = '<script type="text/javascript">mobbr.button' . $buttontype. '(' . '"", "' . $currency . '");</script>';
```

It needs to have the full URL of the question it acts upon. Like:

```
        $buttonhtml = '<script type="text/javascript">mobbr.button' . $buttontype. '(' . <URL> . '"", "' . $currency . '");</script>';
```

I figure you know this by head, I would need to dive into QA again. 

And can you send me your Mobbr name, than I will send you the money. Our system cannot reward pull-requests yet. I will add that soon. This was a unforeseen use-case ;)

**Comment by pupi1985** [comment]
Oh ok. I took the original JS code. It seems mobbr fetches the data from the url you sent in JS and then parses some tag in the `<head>` section. In case no URL is set I guess the JS library is setting it or maybe using the HTTP referer tag. So as there isn't actually a question in the question list you need to force the URL in the JS so that mobbr can parse each of them.

Now, the fix is simple. However, there might be a few issues which I think have no possible solution. The _minimal_ form of a URL for a question is `http://www.site.com/123`, where `123` stands for the id of the question. The thing is you can configure different URL types to use (some might require to change an .htaccess file) which results in all these URLs being able to reach question `123`:
- /123
- /123/why-do-birds-sing (requires htaccess file) 
- /123/ (requires htaccess file. Actually this is a variation of the previous one with a length of 0 assigned to titles in URLs, which is another setting in Q2A)
- /index.php/123/why-do-birds-sing 
- /?qa=123/why-do-birds-sing 
- /?qa=123&qa_1=why-do-birds-sing 
- /index.php?qa=123&qa_1=why-do-birds-sing

It doesn't mean all of them would be enabled at a given time but they can be changed. So my question here is: what impact does this have on mobbr? This is related to how you match 2 or more different URLs, e.g., is for you the same http://www.google.com, http://www.google.com?param=val or http://www.google.com/param/val ? Or maybe you perform some kind of custom processing, e.g., "if it comes from github.com then do this otherwise...". Or maybe you can setup an html tag in the `<head>` section to hint it is a Q2A site so that the `/123` only is taken into account.

Having said that, I can add the URL to the JS but which one should I add? I can only think in these 2:
1. The minimal URL: `/123` (this one would require you to know `/123` is the same as `/123/why-do-birds-sing`)
2. The URL that generates Q2A in the question lists (i.e. the clickable link) for **currently** selected URL schema: it could be any of the ones listed above except for `/123`, as it is not a scheme actually.

Let me know the approach that best suits your needs. Oh, I've created an account with this same username in mobbr.

**Comment by patricksavalle** [comment]
Aha. Very good. Your observation is correct, the Mobbr API does a callback to the URL that was sent by the button and then picks up the metadata over there.

What happens next is important for the choice we need to make: our API uses the <link rel="canonical"> tag in the HTML to do the actual payment to. 

So, it is not important which URL scheme we use, as long it reaches the correct page AND it is a full URL. Once our API reaches that pages it will normalize the URL itself.

I will send you the money.

**Comment by pupi1985** [comment]
Oh ok. So if it is a link for mobbr internal usage (I mean, it shouldn't be exposed to the user) then let's keep the shortest possible absolute URL (that will save a few bytes). I've added the needed commit to this branch so you can pull it again and test it. Let me know if you have any issues. Thanks!

**Comment by patricksavalle** [comment]
Ow sh*t :)

@pupi1985, I made a mistake explaining this to you... 

The URL does need to be the EXACT same URL as in the canonical-tag of the actual page. Is this still possible to add? Only if it doesn't take you a lot of time. 

P.S. I fixed it myself, I took a quick look, it wasn't that hard thanks to the clear structure of the QA software and your code.

**Comment by pupi1985** [comment]
Oh ok. I've just taken a look at how you fixed it and I would have done the same thing. Just one very small tweak. Actually, I should have gone for this on first place. In order to generate it exactly how the core does then you should use `qa_q_path_html` instead of `qa_q_path`. Parameters are the same, so just add those 5 characters :)

Reference: https://github.com/q2a/question2answer/blob/dd67d0fda2deccf7cc16f26da3663e4caa562808/qa-include/app/format.php#L292

**Comment by patricksavalle** [comment]
Done :)

**Pull request merged**
